[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "maltego-transforms-std-entities"
version = "1.0.1"
description = "Python classes for the Maltego standard entity catalog."
authors = [
    "Maltego Technologies GmbH",
]
license = "MIT"
readme = "README.md"
packages = [
    { include = "maltego", from = "src" },
]
include = [
    "CHANGELOG.md",
    "LICENSE",
]

[tool.poetry.urls]
Documentation = "https://docs.maltego.com/en/support/solutions/articles/15000062357-standard-entities-overview"

[tool.poetry.dependencies]
python = ">=3.11,<3.15"
maltego-transforms = ">=1.0.1,<4"

[tool.poetry.group.dev.dependencies]
commitizen = ">=4,<5"
pytest = ">=7,<10"
pytest-cov = "^4"
ruff = ">=0.14.11"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = [
    "F403",
    "F405",
]

[tool.commitizen]
name = "cz_conventional_commits"
version_provider = "poetry"
tag_format = "v$version"
update_changelog_on_bump = true
